package com.duke.db.beans;
// Generated 21-Jan-2017 1:35:47 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UserRoles generated by hbm2java
 */
@Entity
@Table(name = "UserRoles", catalog = "invoicedb")
public class UserRoles implements java.io.Serializable {

	private UserRolesId id;

	public UserRoles() {
	}

	public UserRoles(UserRolesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "role", column = @Column(name = "Role", nullable = false, length = 100)),
			@AttributeOverride(name = "loginEmail", column = @Column(name = "loginEmail", nullable = false, length = 100)) })
	public UserRolesId getId() {
		return this.id;
	}

	public void setId(UserRolesId id) {
		this.id = id;
	}

}
