package com.duke.db.beans;
// Generated 21-Jan-2017 1:35:47 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserRolesId generated by hbm2java
 */
@Embeddable
public class UserRolesId implements java.io.Serializable {

	private String role;
	private String loginEmail;

	public UserRolesId() {
	}

	public UserRolesId(String role, String loginEmail) {
		this.role = role;
		this.loginEmail = loginEmail;
	}

	@Column(name = "Role", nullable = false, length = 100)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "loginEmail", nullable = false, length = 100)
	public String getLoginEmail() {
		return this.loginEmail;
	}

	public void setLoginEmail(String loginEmail) {
		this.loginEmail = loginEmail;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserRolesId))
			return false;
		UserRolesId castOther = (UserRolesId) other;

		return ((this.getRole() == castOther.getRole()) || (this.getRole() != null && castOther.getRole() != null
				&& this.getRole().equals(castOther.getRole())))
				&& ((this.getLoginEmail() == castOther.getLoginEmail())
						|| (this.getLoginEmail() != null && castOther.getLoginEmail() != null
								&& this.getLoginEmail().equals(castOther.getLoginEmail())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getRole() == null ? 0 : this.getRole().hashCode());
		result = 37 * result + (getLoginEmail() == null ? 0 : this.getLoginEmail().hashCode());
		return result;
	}

}
